### ISSUE TITLE
Otterize network-mapper invalid URL escape

### ISSUE THREAD

**Issue by jonaszlasut** [otterize/network-mapper#162]
We're trying to use otterize network-mapper with rancher based cluster, which has cluster:server field in kubeconfig that looks like this

```
clusters:
- cluster:
    server: https://RANCHER_URL/k8s/clusters/CLUSTER_NAME
  name: CLUSTER_NAME
```

However when running `otterize network-mapper list` we're getting the below error

```
Error: error upgrading connection: error creating request: parse "https://<RANCHER_URL>%2Fk8s%2Fclusters%2FCLUSTER_NAME/api/v1/namespaces/otterize-system/pods/otterize-network-mapper-65b5b9c654-tkgvq/portforward": invalid URL escape "%2F"
```
